name: sertton
description: "A e-commerce app for selling truck products."
publish_to: "none"
version: 1.0.15

environment:
  flutter: "3.38.7"
  sdk: ^3.10.7

dependencies:
  animate_do: ^4.2.0
  dio: ^5.9.0
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.2.0
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^10.12.0
  go_router: ^17.0.1
  intl: ^0.20.2
  lottie: ^3.3.2
  mask_text_input_formatter: ^2.9.0
  package_info_plus: ^9.0.0
  shadcn_flutter: 0.0.47
  shared_preferences: ^2.5.4
  signals: ^6.3.0
  signals_flutter: ^6.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  mocktail: ^1.0.4
  network_image_mock: ^2.1.1
  url_launcher_platform_interface: any
  plugin_platform_interface: any

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/sertton-logo.png
    - assets/lotties/truck.json

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/sertton-icon.png"
  adaptive_icon_foreground: "assets/images/sertton-icon.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png

  android_12:
    image: assets/images/splash.png
    icon_background_color: "#ffffff"

  fullscreen: true
